import AnimatedText from "../Components/AnimatedText";
import { LinkArrow } from "../Components/Icons";
import Layout from "../Components/Layout";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Dashday from "../../public/images/svgs/dash_day.svg";
import DashNight from "../../public/images/svgs/dash_night.svg";

import {CustomLink} from "../Components/Navbar"
import { RiContactsBookFill } from "react-icons/ri";
import LightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg";
import Transitions from "../Components/Transitions";
import { ImUserTie } from "react-icons/im";
import { FaExternalLinkAlt } from "react-icons/fa";


export default function Home() {
  return (
    <>
      <Head>
        <title>Iqbal | Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Transitions />
      <main className="flex items-center text-dark w-full min-h-screen dark:text-light noscroll">
        
          <article className="flex min-h-screen items-center text-dark dark:text-light sm:items-start">
          <Layout>
          <div className="flex w-full items-start justify-between md:flex-col">
            <div className="w-1/2 lg:hidden md:inline-block md:w-full">
              <Image
                src={DashNight}
                alt={"DEVELOPER IMAGE"}
                className="w-full lg:h-auto lg:w-full md:h-200 md:inline-block md:w-full"
                priority
              />
            </div>
            <div className="flex w-1/2 flex-col items-center self-center lg:w-full lg:text-center">
              <AnimatedText
                text="Hey! This is "
                className="!text-4xl  !text-left xl:!text-3xl lg:!text-center lg:!text-4xl md:!text-3xl sm:!text-2xl"
              />
              <AnimatedText
                text="Iqbal Mohammad Rhidwan "
                className="!text-5xl  !text-left xl:!text-5xl lg:!text-center lg:!text-5xl lg:!mb-1  md:!text-5xl sm:!text-xl sm:!mb-1"
                fontColour="!text-primary"
              />
              <AnimatedText 

                text="Freelance Programmer & Web Developer."
                className="!text-xl  !text-left xl:!text-xl lg:!text-center lg:!text-xl lg:!mb-1  md:!text-xl sm:!text-md sm:!mb-1"
              
              />
              
              {/* <p className="my-4 text-base font-medium md:text-sm sm:text-xs ">
                As a Full-Stack Developer, I am well versed in Web
                Development,MERN Development,Backend Development. With prior
                interest in UX and UI, I also have a proficiency in creating
                efficient, effective and engaging web designs. Kindly, explore
                my previous works in Projects section that appropriately
                showcases my expertise in the field.
              </p> */}
              <div className="flex flex-wrap  items-center self-start mt-2 lg:self-center">
               
                <Link
                  href={"http://example.com"}
                  target="_self"
                  className="flex items-center mt-1.5 bg-dark text-light p-2 rounded-lg text-lg font-semibold dark:text-dark dark:bg-light hover:dark:bg-dark hover:dark:text-light hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark hover:dark:border-light md:p-2 md:px-4 md:text-base"
                >
                  Resume  <FaExternalLinkAlt className="ml-2" />
                </Link>

              <Link
              className="ml-4 flex items-center mt-1.5 text-lg font-medium capitalize text-dark underline dark:text-light md:text-base"
              href={"https://mail.google.com/mail/u/0/?fs=1&tf=cm&source=mailto&to=iqbalrhidwan52@gmail.com"}
              target="_blank"
              >
              Contact
              </Link>

               
               
              </div>
             
            </div>
          </div>
        </Layout>
          </article>
          
        <div className="absolute w-24 right-8 bottom-16  inline-block">
          <Image
            src={LightBulb}
            alt="Bulb"
            className="w-full h-auto md:hidden"
          />
        </div>
      </main>
    </>
  );
}
